//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbProgrammProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programms
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
    }
}
